// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E test-unused-component 1`] = `
[1] openapi.yaml:4:12 at #/info/version

Expected type 'string' but got 'number'

2 | info:
3 |   title: Example OpenAPI 3 definition.
4 |   version: 1.0
  |            ^^^
5 |
6 | paths:

error was generated by spec rule.


[2] openapi.yaml:1:1 at #/

OpenAPI servers must be present.

 1 | openapi: 3.0.0
   | ^^^^^^^^^^^^^^
 2 | info:
   | ^^^^^
 … | < 8 more lines >
11 |           description: example description
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning was generated by no-empty-servers rule.



❌ Validation failed with 1 error and 1 warning. 

run with \`--generate-exceptions\` to add all messages to exceptions file


`;
